package com.nubian.ai.runtime.mcp.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;

/**
 * Result returned to the server after the client fulfils a {@code sampling/createMessage}
 * request.
 *
 * <p>Per the MCP spec (2025-11-25): the result carries the model's response, the actual
 * model identifier used, and the reason generation stopped. The {@code content} field
 * mirrors the same single-or-list flexibility as {@link SamplingMessage#content()}.
 *
 * @param role       Role of the generated message — always {@link Role#ASSISTANT}.
 * @param content    Single content block or array of content blocks generated by the model.
 * @param model      Identifier of the model that actually produced the completion.
 * @param stopReason Why the model stopped generating tokens.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateMessageResult(
        @JsonProperty("role") Role role,
        @JsonProperty("content") JsonNode content,
        @JsonProperty("model") String model,
        @JsonProperty("stopReason") StopReason stopReason) {

    public CreateMessageResult {
        if (role == null) {
            throw new IllegalArgumentException("CreateMessageResult.role must not be null");
        }
        if (content == null) {
            throw new IllegalArgumentException("CreateMessageResult.content must not be null");
        }
    }
}
